name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - test
        - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: .next

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, test, production]
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: .next
    - name: Deploy to ${{ matrix.environment }}
      if: |
        (github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.environment == 'development') ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == matrix.environment)
      run: |
        # Add your deployment script here
        echo "Deploying to ${{ matrix.environment }} environment"